import { IllegalArgumentException } from "effect/Cause";
export const isObj = (u: unknown) => typeof u === "object" && u !== null;
export const throwIllegalArgumentException = (message: string): never => {
  throw new IllegalArgumentException(message);
};
export const Branch2TypeKey = "Branch2";
export const Branch3TypeKey = "Branch3";
export const NodeTypeKey = "Node";
export const OneTypeKey = "One";
export const TwoTypeKey = "Two";
export const ThreeTypeKey = "Three";
export const FourTypeKey = "Four";
export const AffixTypeKey = "Affix";
export const EmptyTypeKey = "Empty";
export const SingleTypeKey = "Single";
export const DeepTypeKey = "Deep";
export const FingerTreeTypeKey = "FingerTree";
export const NilTypeKey = "Nil";
export const ViewTypeKey = "View";
export const Branch2TypeId = Symbol.for(Branch2TypeKey);
export const Branch3TypeId = Symbol.for(Branch3TypeKey);
export const NodeTypeId = Symbol.for(NodeTypeKey);
export const OneTypeId = Symbol.for(OneTypeKey);
export const TwoTypeId = Symbol.for(TwoTypeKey);
export const ThreeTypeId = Symbol.for(ThreeTypeKey);
export const FourTypeId = Symbol.for(FourTypeKey);
export const AffixTypeId = Symbol.for(AffixTypeKey);
export const EmptyTypeId = Symbol.for(EmptyTypeKey);
export const SingleTypeId = Symbol.for(SingleTypeKey);
export const DeepTypeId = Symbol.for(DeepTypeKey);
export const FingerTreeTypeId = Symbol.for(FingerTreeTypeKey);
export const NilTypeId = Symbol.for(NilTypeKey);
export const ViewTypeId = Symbol.for(ViewTypeKey);
export type Branch2TypeId = typeof Branch2TypeId;
export type Branch3TypeId = typeof Branch3TypeId;
export type NodeTypeId = typeof NodeTypeId;
export type OneTypeId = typeof OneTypeId;
export type TwoTypeId = typeof TwoTypeId;
export type ThreeTypeId = typeof ThreeTypeId;
export type FourTypeId = typeof FourTypeId;
export type AffixTypeId = typeof AffixTypeId;
export type EmptyTypeId = typeof EmptyTypeId;
export type SingleTypeId = typeof SingleTypeId;
export type DeepTypeId = typeof DeepTypeId;
export type FingerTreeTypeId = typeof FingerTreeTypeId;
export type NilTypeId = typeof NilTypeId;
export type ViewTypeId = typeof ViewTypeId;
